In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## EDA ##

Primero me traigo el DF que cree que tiene las 10 monedas que mas market cap tienen, y ademas tiene el id, el nombre, el ranking segun el market cap, el volumen total, el precio maximo en las ultimas 24 hs y el precio minimo en las ultimas 24 hs (como trae datos actuales la ultima vez que lo actualice fue el 21/08), cambio de precio en las ultimas 24 hs y porcentaje de cambio de precio, los valores historicos maximos y minimos y sus porcentajes y sus fechas.

In [20]:
top10= pd.read_csv(r'C:\Users\flori\Desktop\DATA SCIENCE\LABS\Trabajos\tp2\Proyecto2_Data_Analytics\ETL\10cripto.csv')

In [21]:
#Miro el tipo de dato 
top10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                10 non-null     object
 1   name                              10 non-null     object
 2   current_price                     10 non-null     float64
 3   market_cap                        10 non-null     int64
 4   market_cap_rank                   10 non-null     int64
 5   total_volume                      10 non-null     int64
 6   high_24h                          10 non-null     float64
 7   low_24h                           10 non-null     float64
 8   price_change_24h                  10 non-null     float64
 9   price_change_percentage_24h       10 non-null     float64
 10  market_cap_change_24h             10 non-null     float64
 11  market_cap_change_percentage_24h  10 non-null     float64
 12  ath                               10 non-null     float64
 13  ath_change_percentage             10 non-null     float64
 14  ath_date                          10 non-null     object
 15  atl                               10 non-null     float64
 16  atl_change_percentage             10 non-null     float64
 17  atl_date                          10 non-null     object
dtypes: float64(11), int64(3), object(4)
memory usage: 1.5+ KB

In [22]:
#transformo la fecha en datetime porque esta en str
top10['ath_date']= pd.to_datetime(top10['ath_date'])
top10['atl_date']=pd.to_datetime(top10['atl_date'])

In [23]:
top10.describe()

,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,market_cap_change_24h,market_cap_change_percentage_24h,ath,ath_change_percentage,atl,atl_change_percentage
count,10.000000,1.000000e+01,10.00000,1.000000e+01,10.000000,10.000000,10.000000,10.000000,1.000000e+01,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2946.004322,9.123663e+10,5.50000,4.651914e+09,2975.748696,2900.082192,-15.833221,-0.130222,-3.174044e+08,0.027868,7970.881158,-66.215195,55.315579,105567.711604
std,8105.103844,1.566499e+11,3.02765,5.841175e+09,8182.667304,7993.992231,38.494632,1.234547,9.405012e+08,1.180583,21549.744399,27.284529,151.728563,191933.030743
min,0.063289,8.424042e+09,1.00000,5.321024e+07,0.064087,0.060500,-122.311207,-1.778330,-2.144793e+09,-1.520910,0.731578,-92.060000,0.000087,13.925030
25%,0.639189,1.026696e+10,3.25000,4.032522e+08,0.643099,0.629502,-15.445747,-1.039862,-1.213178e+08,-0.608467,1.762500,-89.674612,0.024394,493.276640
50%,10.805500,2.668597e+10,5.50000,9.537524e+08,11.027500,10.328573,0.000176,0.024300,-5.307710e+06,-0.041050,131.680000,-67.474410,0.466890,11635.409155
75%,1286.497500,7.040550e+10,7.75000,9.209118e+09,1303.812500,1249.110000,0.000275,0.166453,5.671315e+07,0.281627,3793.755000,-63.298977,0.801365,64202.398532
max,25934.000000,5.051708e+11,10.00000,1.497428e+10,26183.000000,25575.000000,5.620000,2.686990,9.025285e+08,2.804110,69045.000000,-14.739160,482.900000,540014.329550