# EXCHANGES
* Me conecto a la API de CoinGecko y selecciono las primeras 20 exchange del ranking

In [1]:
import pandas as pd
import requests

url = "https://api.coingecko.com/api/v3/exchanges"

response = requests.get(url)
exchanges = response.json()

exchange_data = []

for exchange in exchanges:
    exchange_data.append({
        'ID': exchange['id'],
        'Nombre': exchange['name'],
        'año_inicio': exchange["year_established"],
        'Pais': exchange["country"],
        'Score_confianza': exchange["trust_score"],
        'Ranking_sc':exchange["trust_score_rank"],
        'Vol_trans_btc_24hs': exchange["trade_volume_24h_btc"]
    })

df = pd.DataFrame(exchange_data)

In [2]:
df

,ID,Nombre,año_inicio,Pais,Score_confianza,Ranking_sc,Vol_trans_btc_24hs
0,binance,Binance,2017.0,Cayman Islands,10.0,1,213925.564183
1,gdax,Coinbase Exchange,2012.0,United States,10.0,2,33320.972154
2,bybit_spot,Bybit,2018.0,British Virgin Islands,10.0,3,26983.552437
3,kraken,Kraken,2011.0,United States,10.0,4,16739.551984
4,kucoin,KuCoin,2014.0,Seychelles,10.0,5,10122.313786
...,...,...,...,...,...,...,...
95,velodrome-finance-v2,Velodrome Finance v2,NaN,None,6.0,96,157.210074
96,biswap,Biswap,NaN,None,6.0,97,152.097932
97,traderjoe-v2-1-arbitrum,TraderJoe V2.1 (Arbitrum),NaN,None,6.0,98,148.260294
98,bit_com,BIT,2020.0,Seychelles,6.0,99,3541.716668
99,nominex,Nominex,2019.0,Seychelles,6.0,100,288.070641

In [3]:
df_top20= df.head(20)

In [4]:
df_top20

,ID,Nombre,año_inicio,Pais,Score_confianza,Ranking_sc,Vol_trans_btc_24hs
0,binance,Binance,2017.0,Cayman Islands,10.0,1,213925.564183
1,gdax,Coinbase Exchange,2012.0,United States,10.0,2,33320.972154
2,bybit_spot,Bybit,2018.0,British Virgin Islands,10.0,3,26983.552437
3,kraken,Kraken,2011.0,United States,10.0,4,16739.551984
4,kucoin,KuCoin,2014.0,Seychelles,10.0,5,10122.313786
5,bitfinex,Bitfinex,2012.0,British Virgin Islands,10.0,6,2729.463844
6,binance_us,Binance US,2019.0,United States,10.0,7,299.696680
7,okex,OKX,2017.0,Seychelles,9.0,8,20937.906486
8,huobi,Huobi,2013.0,Seychelles,9.0,9,41167.887839
9,gate,Gate.io,NaN,Cayman Islands,9.0,10,15227.966066
10,bitget,Bitget,2018.0,Seychelles,9.0,11,14224.034179
11,crypto_com,Crypto.com Exchange,2019.0,Malta,9.0,12,5561.367450
12,gemini,Gemini,2014.0,United States,9.0,13,706.810714
13,digifinex,DigiFinex,2018.0,Seychelles,8.0,14,29850.364670
14,coinw,CoinW,2017.0,United Arab Emirates,8.0,15,23934.436442
15,mxc,MEXC,2018.0,Seychelles,8.0,16,18233.927782
16,whitebit,WhiteBIT,2018.0,Lithuania,8.0,17,14493.070433
17,bingx,BingX,2018.0,British Virgin Islands,8.0,18,8332.203669
18,deepcoin,Deepcoin,2018.0,Seychelles,8.0,19,7590.108058
19,btse,BTSE,2018.0,British Virgin Islands,8.0,20,10924.341255

In [5]:
df_top20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20 non-null     object
 1   Nombre              20 non-null     object
 2   año_inicio          19 non-null     float64
 3   Pais                20 non-null     object
 4   Score_confianza     20 non-null     float64
 5   Ranking_sc          20 non-null     int64
 6   Vol_trans_btc_24hs  20 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.2+ KB

In [6]:
df_top20.to_csv('exchange.csv', index=False)