# Datos historicos de las 10 criptomonedas
* Desde=
* Hasta

In [2]:
import pandas as pd
import datetime as dt
import time as t
import plotly.graph_objects as go
from plotly.offline import plot

In [3]:
import requests
base_url = "https://api.coingecko.com/api/v3"

In [4]:
# Con esta funcion me conecto a la funcion que trae datos historicos, elijo market cap, total vol y precio todo en USD
def get_price_and_market_cap(coin_id, start_date, end_date):
    endpoint = f"/coins/{coin_id}/market_chart/range"
    params = {
        "vs_currency": "usd",
        "from": start_date,
        "to": end_date
    }
    url = base_url + endpoint
    response = requests.get(url, params=params)
    data = response.json()
    
    prices = data.get("prices", [])
    market_caps = data.get("market_caps", [])
    total_volumes = data.get("total_volumes", [])
    
    # Crear DataFrames para precios, capitalización de mercado y volúmenes totales
    price_df = pd.DataFrame(prices, columns=["FECHAS", "PRECIO-usd"])
    price_df["FECHAS"] = pd.to_datetime(price_df["FECHAS"], unit="ms")
    
    market_cap_df = pd.DataFrame(market_caps, columns=["FECHAS", "MARKET_CAP-usd"])
    market_cap_df["FECHAS"] = pd.to_datetime(market_cap_df["FECHAS"], unit="ms")
    
    volume_df = pd.DataFrame(total_volumes, columns=["FECHAS", "TOTAL_VOLUMES"])
    volume_df["FECHAS"] = pd.to_datetime(volume_df["FECHAS"], unit="ms")
    
    # Combinar DataFrames
    df = pd.merge(price_df, market_cap_df, on="FECHAS", how="inner")
    df = pd.merge(df, volume_df, on="FECHAS", how="inner")
    
    df["COIN_ID"] = coin_id
    
    return df

In [5]:
### de esta manera transformo una fecha y un horario a UNIX
from datetime import datetime

# Especifica la fecha y hora deseada
fecha_deseada = datetime(2020, 1, 1, 12, 0, 0)

# Calcula el valor de marca de tiempo UNIX
timestamp_unix = int(fecha_deseada.timestamp())

print(timestamp_unix)

1577890800

In [6]:
from datetime import datetime

# Especifica la fecha y hora deseada
fecha_deseada = datetime(2023, 8, 20, 12, 0, 0)

# Calcula el valor de marca de tiempo UNIX
timestamp_unix = int(fecha_deseada.timestamp())

print(timestamp_unix)

1692543600

In [7]:
coin_id = "bitcoin"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # 20 Agosto 2023

price_history_bitcoin2 = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_bitcoin2

         FECHAS    PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES  COIN_ID
0    2020-01-02   7193.754668    1.304230e+11   1.812352e+10  bitcoin
1    2020-01-03   6963.853354    1.262808e+11   2.031319e+10  bitcoin
2    2020-01-04   7300.346935    1.327663e+11   3.101578e+10  bitcoin
3    2020-01-05   7351.377053    1.334747e+11   2.061164e+10  bitcoin
4    2020-01-06   7349.972248    1.333890e+11   2.192922e+10  bitcoin
...         ...           ...             ...            ...      ...
1322 2023-08-16  29170.490397    5.674983e+11   1.152340e+10  bitcoin
1323 2023-08-17  28754.197021    5.599826e+11   1.480998e+10  bitcoin
1324 2023-08-18  26501.587270    5.160269e+11   2.996559e+10  bitcoin
1325 2023-08-19  26042.838257    5.068158e+11   1.806235e+10  bitcoin
1326 2023-08-20  26104.778631    5.080877e+11   3.355039e+09  bitcoin

[1327 rows x 5 columns]

In [8]:
price_history_bitcoin2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1327 entries, 0 to 1326
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FECHAS          1327 non-null   datetime64[ns]
 1   PRECIO-usd      1327 non-null   float64
 2   MARKET_CAP-usd  1327 non-null   float64
 3   TOTAL_VOLUMES   1327 non-null   float64
 4   COIN_ID         1327 non-null   object
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 52.0+ KB

In [9]:
price_history_bitcoin2.to_csv('bitcoin.csv', index=False)

In [10]:
## lo hago con todas las monedas
coin_id = "ethereum"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_et = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_et

         FECHAS   PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES   COIN_ID
0    2020-01-02   130.484685    1.423059e+10   6.623732e+09  ethereum
1    2020-01-03   127.045258    1.385979e+10   6.497298e+09  ethereum
2    2020-01-04   133.702649    1.461319e+10   9.655245e+09  ethereum
3    2020-01-05   134.136883    1.463621e+10   6.958394e+09  ethereum
4    2020-01-06   135.005714    1.473883e+10   7.260645e+09  ethereum
...         ...          ...             ...            ...       ...
1322 2023-08-16  1826.913128    2.194728e+11   4.416612e+09  ethereum
1323 2023-08-17  1809.460474    2.174445e+11   6.472231e+09  ethereum
1324 2023-08-18  1675.862171    2.014830e+11   2.096277e+10  ethereum
1325 2023-08-19  1660.679110    1.993229e+11   1.185691e+10  ethereum
1326 2023-08-20  1669.233455    2.006764e+11   8.226872e+09  ethereum

[1327 rows x 5 columns]

In [12]:
price_history_et.to_csv('ethereum.csv', index=False)

In [11]:
coin_id = "binancecoin"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_bnb = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_bnb

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES      COIN_ID
0    2020-01-02   13.685902    2.099316e+09   1.847091e+08  binancecoin
1    2020-01-03   13.007171    1.995648e+09   1.573566e+08  binancecoin
2    2020-01-04   13.603276    2.088117e+09   1.772397e+08  binancecoin
3    2020-01-05   13.794575    2.116144e+09   1.699075e+08  binancecoin
4    2020-01-06   14.006361    2.147451e+09   1.834075e+08  binancecoin
...         ...         ...             ...            ...          ...
1322 2023-08-16  236.607285    3.644085e+10   4.801982e+08  binancecoin
1323 2023-08-17  232.095486    3.568297e+10   5.180758e+08  binancecoin
1324 2023-08-18  217.795538    3.355258e+10   9.462674e+08  binancecoin
1325 2023-08-19  215.972916    3.322978e+10   6.146381e+08  binancecoin
1326 2023-08-20  217.075522    3.340955e+10   3.853982e+08  binancecoin

[1327 rows x 5 columns]

In [13]:
price_history_bnb.to_csv('bnb.csv', index=False)

In [14]:
coin_id = "tether"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_tet = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_tet

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES COIN_ID
0    2020-01-02    0.999508    4.286266e+09   2.051133e+10  tether
1    2020-01-03    0.999983    4.288899e+09   2.278512e+10  tether
2    2020-01-04    0.998661    4.283023e+09   3.435977e+10  tether
3    2020-01-05    0.999595    4.287221e+09   2.324231e+10  tether
4    2020-01-06    0.999073    4.281392e+09   2.549920e+10  tether
...         ...         ...             ...            ...     ...
1322 2023-08-16    0.998893    8.308914e+10   1.874669e+10  tether
1323 2023-08-17    0.999750    8.306115e+10   2.316023e+10  tether
1324 2023-08-18    0.996174    8.240478e+10   3.901929e+10  tether
1325 2023-08-19    0.999381    8.284635e+10   2.847330e+10  tether
1326 2023-08-20    1.000243    8.282739e+10   9.788598e+09  tether

[1327 rows x 5 columns]

In [15]:
price_history_tet.to_csv('tether.csv', index=True)

In [16]:
coin_id = "ripple"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_xrp = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_xrp

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES COIN_ID
0    2020-01-02    0.192556    8.341959e+09   1.043386e+09  ripple
1    2020-01-03    0.187433    8.125379e+09   1.082069e+09  ripple
2    2020-01-04    0.192299    8.347737e+09   1.276806e+09  ripple
3    2020-01-05    0.192812    8.353409e+09   9.874215e+08  ripple
4    2020-01-06    0.193816    8.392968e+09   1.151984e+09  ripple
...         ...         ...             ...            ...     ...
1322 2023-08-16    0.609330    3.215351e+10   1.200449e+09  ripple
1323 2023-08-17    0.589253    3.111217e+10   1.563956e+09  ripple
1324 2023-08-18    0.504536    2.666622e+10   2.195107e+09  ripple
1325 2023-08-19    0.505539    2.667860e+10   1.918959e+09  ripple
1326 2023-08-20    0.519734    2.747779e+10   9.296988e+08  ripple

[1327 rows x 5 columns]

In [17]:
price_history_xrp.to_csv('xrp.csv', index=False)

In [18]:
coin_id = "usd-coin"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_usdc = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_usdc

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES   COIN_ID
0    2020-01-02    1.003346    5.202078e+08   2.156181e+08  usd-coin
1    2020-01-03    1.002434    5.199155e+08   2.725911e+08  usd-coin
2    2020-01-04    1.000130    5.188404e+08   3.194660e+08  usd-coin
3    2020-01-05    1.001133    5.189525e+08   2.337284e+08  usd-coin
4    2020-01-06    1.000500    5.179733e+08   2.434995e+08  usd-coin
...         ...         ...             ...            ...       ...
1322 2023-08-16    0.999975    2.603284e+10   3.215612e+09  usd-coin
1323 2023-08-17    1.000939    2.608557e+10   3.877504e+09  usd-coin
1324 2023-08-18    0.995522    2.601172e+10   4.416274e+09  usd-coin
1325 2023-08-19    0.999658    2.599099e+10   4.443167e+09  usd-coin
1326 2023-08-20    1.000504    2.598605e+10   1.939243e+09  usd-coin

[1327 rows x 5 columns]

In [19]:
price_history_usdc.to_csv('usdcoin.csv', index=True)

In [20]:
coin_id = "staked-ether"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_lido = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_lido

        FECHAS   PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES       COIN_ID
0   2020-12-22   617.164997    0.000000e+00   1.375630e+05  staked-ether
1   2020-12-23   617.164997    0.000000e+00   1.375630e+05  staked-ether
2   2020-12-24   596.767711    4.424223e+06   6.710226e+04  staked-ether
3   2020-12-25   611.504712    5.651613e+06   5.433679e+04  staked-ether
4   2020-12-26   624.800420    7.284744e+06   4.593306e+04  staked-ether
..         ...          ...             ...            ...           ...
967 2023-08-16  1826.361340    1.484988e+10   1.829936e+07  staked-ether
968 2023-08-17  1807.898559    1.473226e+10   1.777613e+07  staked-ether
969 2023-08-18  1678.531050    1.370034e+10   2.755366e+07  staked-ether
970 2023-08-19  1659.990165    1.356056e+10   2.526507e+07  staked-ether
971 2023-08-20  1668.863869    1.368345e+10   2.436172e+07  staked-ether

[972 rows x 5 columns]

In [ ]:
## tiene menos columnas porque comienza la moneda en dic 2020

In [21]:
price_history_lido.to_csv('lidostaked.csv', index=False)

In [22]:
coin_id = "cardano"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_cardano = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_cardano

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES  COIN_ID
0    2020-01-02    0.033362    1.038898e+09   7.486784e+07  cardano
1    2020-01-03    0.032618    1.015101e+09   6.383528e+07  cardano
2    2020-01-04    0.033967    1.060794e+09   7.916796e+07  cardano
3    2020-01-05    0.034298    1.067106e+09   7.791814e+07  cardano
4    2020-01-06    0.034427    1.069730e+09   4.883356e+07  cardano
...         ...         ...             ...            ...      ...
1322 2023-08-16    0.281729    9.874705e+09   1.741227e+08  cardano
1323 2023-08-17    0.274852    9.638401e+09   2.347988e+08  cardano
1324 2023-08-18    0.254361    8.918503e+09   3.406436e+08  cardano
1325 2023-08-19    0.263688    9.235486e+09   2.651095e+08  cardano
1326 2023-08-20    0.268186    9.404358e+09   1.410403e+08  cardano

[1327 rows x 5 columns]

In [23]:
price_history_cardano.to_csv('cardano.csv', index=False)

In [24]:
coin_id = "solana"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_sol = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_sol

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES COIN_ID
0    2020-04-11    0.957606    7.827652e+06   9.267267e+07  solana
1    2020-04-12    0.784711    6.173608e+06   4.945869e+07  solana
2    2020-04-13    0.875994    7.269680e+06   3.782101e+07  solana
3    2020-04-14    0.786712    6.302364e+06   1.957921e+07  solana
4    2020-04-15    0.666673    5.306221e+06   1.752353e+07  solana
...         ...         ...             ...            ...     ...
1222 2023-08-16   23.875641    9.697572e+09   4.525215e+08  solana
1223 2023-08-17   22.846368    9.300306e+09   4.952949e+08  solana
1224 2023-08-18   21.646962    8.833376e+09   6.564125e+08  solana
1225 2023-08-19   21.330196    8.681696e+09   4.122202e+08  solana
1226 2023-08-20   21.878330    8.915137e+09   2.541815e+08  solana

[1227 rows x 5 columns]

In [25]:
price_history_sol.to_csv('solana.csv', index=False)

In [26]:
coin_id = "dogecoin"  # Reemplaza con el ID de la moneda que deseas analizar
start_date = "1577890800"  # Fecha de inicio enero 2020
end_date = "1692543600"    # Agosto 2023

price_history_doge = get_price_and_market_cap(coin_id, start_date, end_date)

price_history_doge

         FECHAS  PRECIO-usd  MARKET_CAP-usd  TOTAL_VOLUMES   COIN_ID
0    2020-01-02    0.002026    2.485296e+08   3.857691e+07  dogecoin
1    2020-01-03    0.002008    2.470949e+08   4.608031e+07  dogecoin
2    2020-01-04    0.002049    2.515280e+08   4.086374e+07  dogecoin
3    2020-01-05    0.002189    2.685943e+08   4.619690e+07  dogecoin
4    2020-01-06    0.002070    2.542591e+08   3.253959e+07  dogecoin
...         ...         ...             ...            ...       ...
1322 2023-08-16    0.070818    9.960604e+09   4.857363e+08  dogecoin
1323 2023-08-17    0.067312    9.467163e+09   5.408913e+08  dogecoin
1324 2023-08-18    0.061057    8.590705e+09   8.754130e+08  dogecoin
1325 2023-08-19    0.063189    8.883843e+09   5.861529e+08  dogecoin
1326 2023-08-20    0.063734    8.963900e+09   2.813695e+08  dogecoin

[1327 rows x 5 columns]

In [27]:
price_history_doge.to_csv('dogecoin.csv', index=False)